/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;

/**
 *
 * @author SCC-PC03
 */
public class simpleGUIdarnax extends javax.swing.JFrame {

    /**
     * Creates new form simpleGUIdarnax
     */
    public simpleGUIdarnax() {
        initComponents();
    }

    Color Navcolor = new Color(153,0,153);
    Color Headcolor = new Color(204,0,204);
    Color Bodycolor = new Color(255,204,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        DashPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ReportPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        Navbar.setBackground(new java.awt.Color(153, 0, 153));
        Navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashPane.setBackground(new java.awt.Color(153, 0, 153));
        DashPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashPaneMouseExited(evt);
            }
        });
        DashPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        DashPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 170, 30));

        Navbar.add(DashPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, -1));

        UserPane.setBackground(new java.awt.Color(153, 0, 153));
        UserPane.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        UserPane.setMinimumSize(new java.awt.Dimension(170, 29));
        UserPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserPaneMouseExited(evt);
            }
        });
        UserPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER PAGE");
        jLabel2.setDisplayedMnemonicIndex(0);
        jLabel2.setPreferredSize(new java.awt.Dimension(85, 19));
        UserPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        Navbar.add(UserPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 30));

        ReportPane.setBackground(new java.awt.Color(153, 0, 153));
        ReportPane.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        ReportPane.setMinimumSize(new java.awt.Dimension(170, 29));
        ReportPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportPaneMouseExited(evt);
            }
        });
        ReportPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORTS");
        jLabel3.setMaximumSize(new java.awt.Dimension(72, 19));
        jLabel3.setMinimumSize(new java.awt.Dimension(72, 19));
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 19));
        ReportPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        Navbar.add(ReportPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        jPanel1.add(Navbar);
        Navbar.setBounds(0, 0, 170, 430);

        Header.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Header);
        Header.setBounds(170, 0, 720, 50);

        jDesktopPane1.setBackground(new java.awt.Color(255, 204, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(760, 420));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(170, 50, 720, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashPaneMouseExited
        DashPane.setBackground(Navcolor);
    }//GEN-LAST:event_DashPaneMouseExited

    private void DashPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashPaneMouseEntered
        DashPane.setBackground(Bodycolor);
    }//GEN-LAST:event_DashPaneMouseEntered

    private void UserPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPaneMouseEntered
        UserPane.setBackground(Bodycolor);
    }//GEN-LAST:event_UserPaneMouseEntered

    private void UserPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPaneMouseExited
        UserPane.setBackground(Navcolor);
    }//GEN-LAST:event_UserPaneMouseExited

    private void ReportPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportPaneMouseEntered
        ReportPane.setBackground(Bodycolor);
    }//GEN-LAST:event_ReportPaneMouseEntered

    private void ReportPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportPaneMouseExited
        ReportPane.setBackground(Navcolor);
    }//GEN-LAST:event_ReportPaneMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simpleGUIdarnax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simpleGUIdarnax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simpleGUIdarnax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simpleGUIdarnax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simpleGUIdarnax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashPane;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel ReportPane;
    private javax.swing.JPanel UserPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
